-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 16:20:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cambalachingDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cambalachingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cambalachingDB` DEFAULT CHARACTER SET utf8 ;
USE `cambalachingDB` ;

-- -----------------------------------------------------
-- Table `cambalachingDB`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `ciudad_nombre` VARCHAR(45) NULL,
  `ciudad_activa_bo` BIT NULL,
  PRIMARY KEY (`idciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cliente_nombre` VARCHAR(45) NULL,
  `cliente_alias` VARCHAR(45) NULL,
  `cliente_contrasena` VARCHAR(45) NULL,
  `cliente_ciudad` INT NULL,
  `cliente_correo` VARCHAR(45) NULL,
  `cliente_moderador_bo` BIT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_ciudad_idx` (`cliente_ciudad` ASC),
  CONSTRAINT `fk_cliente_ciudad`
    FOREIGN KEY (`cliente_ciudad`)
    REFERENCES `cambalachingDB`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`intercambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`intercambio` (
  `idintercambio` INT NOT NULL AUTO_INCREMENT,
  `intercambio_cliente_solicita` INT NULL,
  `intercambio_cliente_recibe` INT NULL,
  `intercambio_estatus` INT NULL,
  `intercambioc_fecha_solicitud` DATETIME NULL,
  `intercambio_conformidad1` BIT NULL,
  `intercambio_conformidad2` BIT NULL,
  `intercambio_calificacion1` INT NULL,
  `intercambio_calificacion2` INT NULL,
  PRIMARY KEY (`idintercambio`),
  INDEX `fk_intercambio_cliente_solicita_idx` (`intercambio_cliente_solicita` ASC),
  INDEX `fk_intercambio_cliente_recibe_idx` (`intercambio_cliente_recibe` ASC),
  CONSTRAINT `fk_intercambio_cliente_solicita`
    FOREIGN KEY (`intercambio_cliente_solicita`)
    REFERENCES `cambalachingDB`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intercambio_cliente_recibe`
    FOREIGN KEY (`intercambio_cliente_recibe`)
    REFERENCES `cambalachingDB`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`interes` (
  `idinteres` INT NOT NULL AUTO_INCREMENT,
  `interes_nombre` VARCHAR(45) NULL,
  `interes_activo_bo` BIT NULL,
  PRIMARY KEY (`idinteres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `articulo_cliente` INT NULL,
  `articulo_nombre` VARCHAR(45) NULL,
  `articulo_descripcion` VARCHAR(45) NULL,
  `articulo_categoria` INT NULL,
  `articulo_condiciones` INT NULL,
  `articulo_tiempo` INT NULL,
  `articulo_fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `fk_articulo_interes_idx` (`articulo_categoria` ASC),
  CONSTRAINT `fk_articulo_interes`
    FOREIGN KEY (`articulo_categoria`)
    REFERENCES `cambalachingDB`.`interes` (`idinteres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`intercambio_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`intercambio_articulos` (
  `intercambio_articulos_intercambio` INT NULL,
  `intercambio_articulos_articulo` INT NULL,
  INDEX `fk_intercambio_articulos_intercambio_idx` (`intercambio_articulos_intercambio` ASC),
  INDEX `fk_intercambio_articulos_articulo_idx` (`intercambio_articulos_articulo` ASC),
  CONSTRAINT `fk_intercambio_articulos_intercambio`
    FOREIGN KEY (`intercambio_articulos_intercambio`)
    REFERENCES `cambalachingDB`.`intercambio` (`idintercambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intercambio_articulos_articulo`
    FOREIGN KEY (`intercambio_articulos_articulo`)
    REFERENCES `cambalachingDB`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`articulo_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`articulo_foto` (
  `idarticulo_foto` INT NOT NULL AUTO_INCREMENT,
  `articulo_foto_ruta` VARCHAR(45) NULL,
  `articulo_foto_articuloid` INT NULL,
  PRIMARY KEY (`idarticulo_foto`),
  INDEX `fk_articulo_foto_idx` (`articulo_foto_articuloid` ASC),
  CONSTRAINT `fk_articulo_foto`
    FOREIGN KEY (`articulo_foto_articuloid`)
    REFERENCES `cambalachingDB`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `cita_intercambio` INT NULL,
  `cita_lugar` VARCHAR(45) NULL,
  `cita_fecha` DATETIME NULL,
  `cita_estatus` INT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `fk_cita_intercambio_idx` (`cita_intercambio` ASC),
  CONSTRAINT `fk_cita_intercambio`
    FOREIGN KEY (`cita_intercambio`)
    REFERENCES `cambalachingDB`.`intercambio` (`idintercambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cambalachingDB`.`cliente_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambalachingDB`.`cliente_interes` (
  `idcliente_interes_cliente` INT NULL,
  `cliente_interes_interes` INT NULL,
  INDEX `fk_cliente_interes_cliente_idx` (`idcliente_interes_cliente` ASC),
  INDEX `fk_cliente_interes_interes_idx` (`cliente_interes_interes` ASC),
  CONSTRAINT `fk_cliente_interes_cliente`
    FOREIGN KEY (`idcliente_interes_cliente`)
    REFERENCES `cambalachingDB`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_interes_interes`
    FOREIGN KEY (`cliente_interes_interes`)
    REFERENCES `cambalachingDB`.`interes` (`idinteres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
